remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
title: HELLO, I am Simon Bogutzky, iOS developer.
navigation:
  - title: About me
    url: /
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/
